# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.eblup_core <- function(Xall, yall, vardirall, method = "REML", maxiter = 100L, precision = 1e-4) {
    .Call(`_fastsae_eblup_core`, Xall, yall, vardirall, method, maxiter, precision)
}

.seblup_core <- function(Xall, yall, vardirall, W, method = "REML", maxiter = 100L, precision = 1e-4) {
    .Call(`_fastsae_seblup_core`, Xall, yall, vardirall, W, method, maxiter, precision)
}

