# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eblup_core <- function(X, y, vardir, method = "REML", maxiter = 100L, precision = 1e-4) {
    .Call('_fastsae_eblup_core', PACKAGE = 'fastsae', X, y, vardir, method, maxiter, precision)
}

eblup_core_optimized <- function(X, y, vardir, method = "REML", maxiter = 100L, precision = 1e-4, return_fullP = FALSE) {
    .Call('_fastsae_eblup_core_optimized', PACKAGE = 'fastsae', X, y, vardir, method, maxiter, precision, return_fullP)
}

